version: '3'
services:
  server:
    image: reimashi/toska.photos:latest
    restart: always
    labels:
      traefik.enable: "true"
      traefik.port: "80"
      traefik.frontend.rule: "Host:toska.photos,www.toska.photos,toska.aitorgf.com"
      traefik.frontend.entryPoints: "http"
      traefik.default.protocol: "http"
      traefik.docker.network: "intranet"
      com.centurylinklabs.watchtower.enable: "true"
    networks:
      - intranet
      - internet
  watchtower:
    image: v2tec/watchtower
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      REPO_USER: "reimashi"
      REPO_PASS: ""
    labels:
      com.centurylinklabs.watchtower.enable: "true"
    command: --cleanup --interval 3600 --label-enable
networks:
  intranet:
    external:
      name: intranet
  internet:
    external:
      name: internet
